# A sample TOML config file.

[development]
server = "192.168.1.1"
port = 8080
connection_max = 100
enabled = true

[staging]
server = "192.168.1.2"
port = 8090
connection_max = 200
enabled = true

[production]
server = "192.168.1.3"
port = 9000
connection_max = 5000
enabled = true
